### ISSUE TITLE
FB7510769: Emoji should not be affected by vibrancy

### ISSUE THREAD

**Issue by sindresorhus** [feedback-assistant/reports#70]
- **Date:** 2019-12-27
- **Resolution:** Open
- **Area:** AppKit
- **OS:** macOS 10.15.2
- **Type:** Incorrect/Unexpected Behavior

## Description

For example, if you put an emoji as the title of a `NSMenuItem` (NSMenu is vibrant) and then open the menu over a white background, the emoji will be washed out (reduced opacity). This looks really bad.

Emoji should always be full opacity and should not be affected by vibrancy like normal text is.

See attached screenshots. Notice how much better the emoji looks when the menu item is highlighted.

## Files

<img width="241" alt="emoji-washed-out-2" src="https://user-images.githubusercontent.com/170270/71534912-42772780-2902-11ea-96d6-5fff705c28c4.png">
<img width="810" alt="emoji-washed-out" src="https://user-images.githubusercontent.com/170270/71534913-430fbe00-2902-11ea-8a48-1b516e94d8f7.png">
<img width="825" alt="emoji-normal" src="https://user-images.githubusercontent.com/170270/71534914-430fbe00-2902-11ea-9513-dbc3bb76c918.png">

**Comment by shpakovski** [comment]
@sindresorhus They must have been fixed this in macOS 10.15.4 😅

**Comment by sindresorhus** [comment]
Not for NSMenu, unfortunately.

<img width="105" alt="Screenshot 2020-05-04 at 20 47 38" src="https://user-images.githubusercontent.com/170270/80967217-8d70f080-8e48-11ea-8f34-15b24c38e53f.png">

**Comment by shpakovski** [comment]
Interesting, I checked with Google Chrome before reporting. Maybe they use attachments 😅

<img width="608" alt="Chrome" src="https://user-images.githubusercontent.com/163410/80969349-1de80a80-8e22-11ea-839a-f6bc2d7e9c8f.png">

**Comment by sindresorhus** [comment]
That emoji is not correct either. Notice how it's darker than it should. Albeit the issue is much more apparent in dark mode, I can still see it in your screenshot.

Yours:

<img width="20" alt="Screenshot 2020-05-05 at 00 08 09" src="https://user-images.githubusercontent.com/170270/80987441-a25b7d00-8e64-11ea-975c-0a2da1880969.png">

How it should be:
<img width="35" alt="Screenshot 2020-05-05 at 00 08 24" src="https://user-images.githubusercontent.com/170270/80987437-a12a5000-8e64-11ea-80e2-3269f8f6b3ff.png">

**Comment by shpakovski** [comment]
Indeed… Sorry for the false alarm 😢

<img width="70" alt="image" src="https://user-images.githubusercontent.com/163410/81040882-0dcd3b00-8eb5-11ea-852d-d7076397585b.png">
